/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ChallengeCodeRouteImport } from './routes/challenge.$code'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiPublicWebhooksDodoRouteImport } from './routes/api/public/webhooks/dodo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeCodeRoute = ChallengeCodeRouteImport.update({
  id: '/challenge/$code',
  path: '/challenge/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDodoRoute = ApiPublicWebhooksDodoRouteImport.update({
  id: '/api/public/webhooks/dodo',
  path: '/api/public/webhooks/dodo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/p/$id': typeof PIdRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/p/$id': typeof PIdRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/p/$id': typeof PIdRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/challenge/$code'
    | '/p/$id'
    | '/api/public/webhooks/dodo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/challenge/$code'
    | '/p/$id'
    | '/api/public/webhooks/dodo'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/challenge/$code'
    | '/p/$id'
    | '/api/public/webhooks/dodo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ChallengeCodeRoute: typeof ChallengeCodeRoute
  PIdRoute: typeof PIdRoute
  ApiPublicWebhooksDodoRoute: typeof ApiPublicWebhooksDodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$code': {
      id: '/challenge/$code'
      path: '/challenge/$code'
      fullPath: '/challenge/$code'
      preLoaderRoute: typeof ChallengeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/dodo': {
      id: '/api/public/webhooks/dodo'
      path: '/api/public/webhooks/dodo'
      fullPath: '/api/public/webhooks/dodo'
      preLoaderRoute: typeof ApiPublicWebhooksDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ChallengeCodeRoute: ChallengeCodeRoute,
  PIdRoute: PIdRoute,
  ApiPublicWebhooksDodoRoute: ApiPublicWebhooksDodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
